# This is a basic workflow to help you get started with Actions

name: MAT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  a:
    strategy:
      fail-fast: false
      matrix:
        ips: ${{ fromJSON( '[["ja","je","ji","jo","ju"],["pa","pe","pi","po","pu"],["ca","ce","ci","co","cu"]]' ) }}
    uses: ./.github/workflows/blank.yml
    with:
      xoxo: matrix.ips
