# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  x:
    uses: ./.github/workflows/blank_1.yml
